services:
  db:
    image: postgres:16-alpine
    container_name: cac_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - cac_postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: cac_backend
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: nginx_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./frontend/public:/usr/share/nginx/html

volumes:
  cac_postgres_data: