services:
  db:
    image: postgres:16-alpine
    container_name: cac_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - cac_postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: cac_backend
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./.env:/app/.env
      - ./logs:/app/logs

  frontend:
    build: ./frontend
    container_name: nginx_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/public:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:ro

volumes:
  cac_postgres_data: